import Head from "next/head";
import Login from "./components/login";
import { useSelector } from "react-redux";
import { selectUser } from "./features/userSlice";
import Main from "./components/main"


export default function Home() {
  const user = useSelector(selectUser)
  console.log(user.user)
  return (
    <div className="h-full bg-gradient-to-bl from-white via-[#1bbb45]/[15%] to-white">
      <Head>
        <title>Application Tracking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-full ">
        {user.user !== undefined?<Login/>:<Main/>}
      </div>
    </div>
  );
}
